// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

// The CLI (migrate/db pull/studio) needs the *direct* (non-pooled) Postgres
// connection — PgBouncer's transaction pooling mode doesn't support the
// advisory locks the schema engine takes during migrations. The running app
// uses the pooled DATABASE_URL instead, via the adapter in src/lib/prisma.ts.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
